# Generated by Django 4.2.2 on 2023-06-27 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('work', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'job',
                'ordering': ['date'],
            },
        ),
    ]
